type=item
items=minecraft:diamond_sword minecraft:netherite_sword
model=optifine/cit/models/melee_scale_x32_obsidian_claymore
texture=chillsear_talwar
nbt.display.Name=regex:Chillsear Talwar|.*\\\\(Chillsear Talwar\\\\)|\\\\(Chillsear Talwar\\\\).*