type=armor
items=minecraft:diamond_boots minecraft:netherite_boots
texture.diamond_layer_1=institute_associate_1
texture.netherite_layer_1=institute_associate_1
nbt.display.Name=pattern:Institute Associate Boots